config/routes.rb
Rails.application.routes.draw do
    get root to: "homes#top"
    resources :lists
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = "投稿が成功しました!!"
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def index
     puts "作成したキー #{ENV['BIRTHDAY_KEY']}"
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    flash[:notice] = "編集しました!!"
    redirect_to list_path(list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    flash[:notice] = "削除しました。"
    redirect_to lists_path
  end

  private
    def list_params
      params.require(:list).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<div class="top-main">
  <div class="top-image">
   <h1>初めてのtop画面制作</h1>
  </div>
  <div class="bottom-image">
  <h2 class="self">自己紹介</h2>
  </div>
  <div class="self-introduction">
    <ul>
      <li>私の名前はM.Uです。</li>
      <li>今年で２７歳です。</li>
      <li>何故エンジニアを目指したかと言いますと<br>
      このままスキル無しで歳をとりたくなかったから<br>
      初めてProgateで触れた時楽しいと思ったからです。<br>
      エンジニア転職が甘くないのは十分承知の上ですが頑張ります！！
      </li>
    </ul>
  </div>
  <div class="enthusiasm">
    <p>人生で一番勉強していきます！<br>
    これからプログラミングの事エンジニアの事教えてください！<br>
    よろしくお願いします！！！！！！！
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleAppDeno</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1 class="headline">All Lists</h1>
    </header>

    <nav>
    <ul class="nav-list">
       <li class="nav-list-item">
       <%= link_to "Top", root_path %>
        </li>
       <li class="nav-list-item">
       <%= link_to "Lists", lists_path %>
       </li>
       <li class="nav-list-item">
       <%= link_to "New List", new_list_path %>
       </li>
    </ul>
    </nav>
    <main>
    <%= yield %>
    </main>

    <footer>
      <h3>初めてのwebアプリ制作</h3>
    </footer>

  </body>
</html>

app/views/lists/edit.html.erb
<div class="edit-main">
 <h1>編集画面</h1>

 <%= form_with model: @list, url:list_path(@list.id), method: :patch do |f| %>

<div class="edit-title">
 <h4>タイトル</h4>
 <%= f.text_field :title %>
</div>

<div class="edit-body">
 <h4>本文</h4>
 <%= f.text_area :body %>
</div>

<div class="edit-image">
 <h4>画像</h4>
 <%= f.file_field :image, accept: "image/*" %>
</div>

<div class="edit-submit">
 <%= f.submit "保存" %>
</div>
<% end %>
</div>

app/views/lists/index.html.erb
<div>
 <%= flash[:notice] %>
</div>
<div class= "list-wrap">

<% @lists.each do |list| %>
 <div class= "list-box">
   
   <%if list.image.attached? %>
   <%= image_tag list.image, size: "200x200" %>
   <% else %>
   <%= image_tag "no_image", size: "200x200" %>
   <% end %>
   <div class="list-comment">
     <span class="list-body"><%= list.body %></span>
     <span class="list-title"><%=link_to list.title,list_path(list.id) %></span>
     
   </div>
 </div>
 <% end %>
</div>

app/views/lists/new.html.erb
<div class="new-list">
<h1>新規登録</h1>
<div class="error-box">
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

<%= form_with model: @list, url: "/lists",method: :post do |f| %>

<div class="new-title">
 <h4>タイトル</h4>
 <%= f.text_field :title %>
</div>

<div class="new-body">
  <h4>本文</h4>
  <%= f.text_area :body %>
</div>

<div class="new-image">
 <h4>画像</h4>
 <%= f.file_field :image, accept: "image/*" %>
</div>
<div class="new-submit">
 <%= f.submit "投稿" %>
</div>
 <% end %>
</div>

app/views/lists/show.html.erb
<div>
 <%= flash[:notice] %>
</div>

<div class="show-list">
  <div class="show-title">
    <h2>タイトル</h2>
    <p><%= @list.title %></p>
  </div>
   <div class="show-body">
    <h2>本文</h2>
    <p><%= @list.body %></p>
  </div>
 <div class="show-image">
  <h2>画像</h2>
  <% if @list.image.attached? %>
  <%= image_tag @list.image,size: "300x300" %>
  <%else%>
  <%= image_tag "no_image",size: "300x300" %>
  <% end %>
 </div>
 <div class="show-link">
  <%= link_to "編集",edit_list_path(@list.id) %>
  <%= link_to "削除",list_path(@list.id),method: :delete, "data-confirm" => "本当に削除しますか？" %>
 </div>
</div>